# This file is used to configure the application properties.
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/swe304"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
