# This file is used to configure the application properties.
spring:
  datasource:
    url: "jdbc:sqlserver://travula-sql.database.windows.net:1433;database=swe304"
    username: travula
    password: 565829489766263779merhaba.
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
